name: Publish to Anaconda Cloud
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Publish to Anaconda Cloud tags'  
jobs:
  Publish-to-Anaconda-Cloud:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - run: echo "This job was triggered by ${{ github.event_name }}."
      - run: echo "This job is now running on ${{ runner.os }}."
      - run: echo "The branch name is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: s-weigand/setup-conda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Which version
        run: which python
      - name: Install conda packages
        run: conda install conda-build anaconda-client
      - name: Build and publish
        run: conda build ${{ github.workspace }}/conda.recipe --user ${{secrets.ANACONDA_USER}} --token ${{secrets.ANACONDA_TOKEN}}
      - run: echo "This job's status is ${{ job.status }}."
