name: Start readthedocs build
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Start readthedocs build tags'  
jobs:
  start-readthedocs-build:
    runs-on: "ubuntu-latest"
    steps:
      - run: curl -d "token=${{secrets.READTHEDOCS_TOKEN}}" -X POST https://readthedocs.org/api/v2/webhook/pyckmeans/163759/
